### ISSUE TITLE
Control surface setup

### ISSUE THREAD

**Issue by Crzyrndm** [Crzyrndm/B9-PWings-Fork#10]
Pitch and roll inputs are getting switched. presumably the control surfaces are using the wrong axis somewhere. Possibly in part setup not code

**Comment by Crzyrndm** [comment]
cause is mirror axis using -ve scaling. Might need to switch materials in an interesting way for mirrored control surfaces

**Comment by ghost** [comment]
Hey.

I'm a bit new to updating mods through GitHub.  Do you mind giving me a quick tutorial or a link to a good one?

Thanks,

-defarm

**Comment by Crzyrndm** [comment]
1) Download the zip from the [releases](https://github.com/Crzyrndm/B9-PWings-Fork/releases) page
2) Install as normal (merge GameData from zip with KSP GameData. If you get "GameData \ GameData", you did it wrong. It should be "GameData/B9_Aerospace_ProceduralWings")

**Comment by ghost** [comment]
Hey, sweet. Thanks. I had done that earlier, thought I had done it wrong because the textures had flipped, realized I could have just changed them, forgot how to do it, and the rest is history. I'll dedicate a flag to you! Cheers!

**Comment by Crzyrndm** [comment]
fixed by not turning the mirrored wing inside out and handling material switching in code
