### ISSUE TITLE
ModularFuelTanks

### ISSUE THREAD

**Issue by kokosGT** [Crzyrndm/B9-PWings-Fork#11]
MFT disables "J" menu for B9-PW Procedural Wing part. 
B9-PW Control Surfaces are working OK

Could you add a patch cfg that will disable MFT for your PWings?

**Comment by Crzyrndm** [comment]
Logs needed, the wings are supposed to be MFT compatible. Also try with [this](https://github.com/Crzyrndm/B9-PWings-Fork/blob/master/GameData/B9_Aerospace_ProceduralWings/Plugins/B9_Aerospace_WingStuff.dll?raw=true) version

**Comment by kokosGT** [comment]
WingStuff.dll from your reply solved it. Thanks!
