### ISSUE TITLE
Menu and mass issues in 1.1.2

### ISSUE THREAD

**Issue by dgeastman** [Crzyrndm/B9-PWings-Fork#12]
I've been helping test RSS/RO on 1.1.2  Using the latest fork of this as linked above, I'm seeing two problems: about half the time in the VAB, the option to press J and configure the wings doesn't appear.  Leaving the VAB scene and coming back will usually, but not always, fix this.  Also, and perhaps more importantly, it's doing something very wonky with mass.  As a test case, I made a sample vessel, nothing more than a probe core and 4 unmodified pwings.  Vessel mass as shown by mechjeb was 2.656t in the VAB, but then on the pad it shows 4.570t.  This was easily reproducible, only happened to vessels with pwings on them, and the difference in vab and pad mass scaled based on how large the wings were.

**Comment by Crzyrndm** [comment]
Will investigate, probably misunderstanding how this is meant to work...

**Comment by Crzyrndm** [comment]
Unable to replicate any mass or menu issues using stock or FAR. Something else is interfering and I need more information to identify the culprit

**Comment by dgeastman** [comment]
NathanKell says the issue was in RealFuels and he's got a fix for it.
