### ISSUE TITLE
reversed control surface

### ISSUE THREAD

**Issue by enjoybeta** [Crzyrndm/B9-PWings-Fork#13]
while i tried to pitch, the wings on 2 sides  acting reversed, which caused serious roll without sas help
(testing under FAR)

**Comment by Crzyrndm** [comment]
I would swear black and blue that I just got done fixing this. Can you confirm it still happens with the [latest release](https://github.com/Crzyrndm/B9-PWings-Fork/releases) and if not I need logs and a MM cache

**Comment by enjoybeta** [comment]
Thank you for reminding me the latest version, it is fixed

**Comment by enjoybeta** [comment]
btw, could you post this mod on SpaceDock, which is the one substitute KerbalStuff. it is a nice mod and would be welcomed by more people
