### ISSUE TITLE
Shader conflicting with other asset bundles

### ISSUE THREAD

**Issue by fallout2077** [Crzyrndm/B9-PWings-Fork#14]
I posted in your thread, but I figured that I should post here too. When this mid is installed alongside RO and it's suggested/recommended mods through CKAN, the wingshader.ksp file stops the KSP EDIT from functioning. Removing or moving the shader file into its own folder solves the issue, but breaks B9 Pwings. Output logs below.

Pwings not installed - https://www.dropbox.com/s/z96756wa94gqo9j/output_log%20%28No-PWings%29.zip?dl=0

Pwings installed - https://www.dropbox.com/s/adn0rjvoigemug7/output_log%20%28With-PWings%29.zip?dl=0

**Comment by Crzyrndm** [comment]
The latest commit uses a loader that isn't the KSP one. Would you mind giving it a spin and seeing if it resolves your issues

**Comment by fallout2077** [comment]
It'd be my pleasure! Allow me to install it and I'll get back to you within the next 10 minutes.

**Comment by fallout2077** [comment]
Upon running KSP, the problem persists. I will uninstall B9 Pwings and see if that truly is still the root of the problem. I'll report back shortly.

**Comment by fallout2077** [comment]
It would seem that B9 Pwings is no longer the cause of the KSPedia-not-appearing issue. I'll do some work tracking down the culprit, and when I finally do, I'll reinstall B9 Pwings and see if the problem has been truly solved. Until then, thank you for your work, Crzyrndm, and have a great day!

**Comment by fallout2077** [comment]
I'm pretty confident that I found the culprit for my issue. Filter Extensions, when installed, stops the KSPedia from appearing when the KSPedia button is pressed. Upon uninstalling Filter Extensions, the problem is solved, and I can view the KSPedia. With this knowledge, would you like me to post an Output Log here, or open up an issue over on your GitHub page for Filter Extensions?

**Comment by Crzyrndm** [comment]
It sounds like the same issue so I'll just copy this across and try again

**Comment by Crzyrndm** [comment]
latest commit to FE uses the same approach. Hopefully this works...

**Comment by fallout2077** [comment]
I'm at work, so I'll have to wait until later to try it out. I'll post here as soon as I have something to report. Thanks for all the hard work, Crzyrndm!

**Comment by fallout2077** [comment]
Until I can try out the FE commit, I suppose this issue can be consider closed, as the most recent commit to B9 Pwings Fork has fixed it?

**Comment by fallout2077** [comment]
The newest FE commit works like a charm; I am able to read the KSP EDIT with both B9 Pwings and FE installed. Thank you very much for your time, and please have a fantastic day!

**Comment by fallout2077** [comment]
Well, I'm going to close the issue, as the latest commit has solved it. Once again, thank you, Crzyrndm.
