### ISSUE TITLE
Lift not functioning correctly with swept wings

### ISSUE THREAD

**Issue by Northstar1989** [Crzyrndm/B9-PWings-Fork#21]
When wings are swept back the Center of Lift will appear to move in the editor, but the wings will BEHAVE as if their Center of Lift is where they would be for straight wings of the same size.

TO TEST: Create an airraft that has neutral stability or slight (but manageable) instability due to Center of Lift being just barely ahead of Center of Mass.   Give it very high wingspan and a somewhat thick chord length in its main wing to amplify the effects of any changes you make to wing sweep on craft stability, as well as high wing thickness and fueled (wet) wings to increase its mass.  Then sweep the wing as far back as you can.

The Center of Lift will APPEAR to move back and make the plane more stable, but the display is lying to you.  Test flying the aircraft before and after introducing wing sweep (save and exit the editor then reliad first- it may be that what is actually occuring is that Lift offset is lost during reloading).  Instead of the aircraft becoming MORE stable, it will become *FAR LESS* stable- as the wing's Lift will continue to act as if it were not swept, but the Center of Mass will still move backwards.

EXPECTED BEHAVIOR:  Introducing wing sweep should offset the Lift of the wing in the direction of wing sweep, not only in the VAB/SPH (which does occur/display correctly), but also in actual FLIGHT.  This currently does not occur, at least on some computers.

**Comment by Crzyrndm** [comment]
Looks like a slight change in KSP behaviour caused CoL/CoP to not follow CoM if unset.

Fixed dll uploaded, please verify :)

**Comment by Northstar1989** [comment]
Appears to be fixed.  However testing identified two new issues:

(1)  Mass of All-Moving B9 PWings is completely unaffected by wing-thickness, unlike srandard B9 Pwings.

(2)  Sweeping backwards standard B9 PWings with attached PWing Control Surfaces inverts PWing Control Surfaces.  So if top-surface was previously facing up, faces down after sweeping wings back far enough and vise-versa (of top faced down, now faces up).

**Comment by Crzyrndm** [comment]
Release made for critical bug.
Mass/Thickness issue is probably common to Control Surfaces as a whole, should be easy to find
Sweep inversion could be a much deeper issue

**Comment by Crzyrndm** [comment]
Dry mass is currently not affected by thickness for any part. Stock mass calculation is governed only by lifting surface area (length x avg. width) following the guidelines posted by NK and Porkjet after 1.0

lift coeff = surface area / 3.52
mass = lift coeff / 10

I see no reason to deviate from this advice.
