### ISSUE TITLE
Shader is broken in KSP 1.4.X

### ISSUE THREAD

**Issue by jrodrigv** [Crzyrndm/B9-PWings-Fork#30]
Hi there,

The only thing pending for this mod to work on KSP 1.4.x is the shader.

Not sure if you plan to upgrade the shader to Unity 2017 but if you don't have time I'm willing to do it.

But I will need the source code of wingShader  (KSP/Specular Layered)

I haven't found it looking at your repo ;(

**Comment by FluffyLogic** [comment]
Please contact Van Disaster at ksp forum.
Here is a [link](https://forum.kerbalspaceprogram.com/index.php?/topic/94621-102-b9-aerospace-procedural-parts-040-updated-090615/&do=findComment&comment=2615899) to a post that implies he has access to wingShader

**Comment by jrodrigv** [comment]
https://github.com/jrodrigv/B9-PWings-Fork/releases

I have already fixed & released this mod.

**Comment by FluffyLogic** [comment]
Yea i found updated version in like 2 minutes later :) I blame this on late night :)
And of course congrats on update ! This mod is indispensable for us SSTO builders :)
