### ISSUE TITLE
No Parts Appear

### ISSUE THREAD

**Issue by Whovian41110** [Crzyrndm/B9-PWings-Fork#4]
Nothing appears in the parts menu.  The only thing I did "wrong" was rename the folder B9_Aerospace to B9_Aerospace_Wings to prevent folders clashing.

**Comment by Crzyrndm** [comment]
The install directory needs to remain B9_Aerospace, or you need to modify the paths in each of the three part .cfgs that specify paths (specifically, the model nodes)
