### ISSUE TITLE
Bottom/Top detection broken for non default orientations in VAB

### ISSUE THREAD

**Issue by hrobertson** [Crzyrndm/B9-PWings-Fork#8]
Rotating the vessel about the vertical axis in the VAB is commonly used to orient the ship for launch along the equator.
This and many other non-default orientations cause the detection of which wing surface is top or bottom to be incorrect and often asymmetrical.

To reproduce in VAB:
1. Place a root part eg FL-T800 fuel tank
2. Attach wings with radial symmetry, perpendicular to the floor of the VAB.
3. Select the fuel tank and rotate the top down so the wings are no longer perpendicular to the floor of the VAB.
4. Continue to rotate about this axis and observe:
a) The bottom (HRSI surface) is the North-most surface rather than the top-most.
b) When wings are parallel to the floor, one has top surface facing up, one facing down.
1. Start again and this time attach wings with mirror symetry. Attach wings such that they are not parallel with eachother, ie at a dihedral/anhedral angle.
2. Rotate 90 degrees about the vertical axis and observe errant top/bottom detection.

**Comment by Crzyrndm** [comment]
For now, working as intended. Will resolve properly at some future time
